import type { Assessment, DomainResult } from "../types/assessment";
import { LevelBadge } from "./ui";

function DomainCard({ d }: { d: DomainResult }) {
  return (
    <div className="pt-card pt-section">
      <div className="pt-page-header" style={{ marginBottom: 12 }}>
        <h3 style={{ margin: 0 }}>{d.rubricDomain}</h3>
        <LevelBadge level={d.performanceLevel} />
      </div>
      {d.summary && <p className="pt-sub" style={{ marginBottom: 12 }}>{d.summary}</p>}

      {d.strengths.length > 0 && (
        <>
          <strong>Strengths</strong>
          <ul>
            {d.strengths.map((s, i) => (
              <li key={i}>{s}</li>
            ))}
          </ul>
        </>
      )}
      {d.areasForGrowth.length > 0 && (
        <>
          <strong>Areas for improvement</strong>
          <ul>
            {d.areasForGrowth.map((s, i) => (
              <li key={i}>{s}</li>
            ))}
          </ul>
        </>
      )}

      {d.evidence.length > 0 && (
        <>
          <strong>Supporting transcript evidence</strong>
          <div style={{ marginTop: 8, display: "flex", flexDirection: "column", gap: 8 }}>
            {d.evidence.map((e) => (
              <div key={e.evidenceId} className="pt-card" style={{ padding: 12 }}>
                <div className="pt-row" style={{ justifyContent: "space-between" }}>
                  <span>
                    <span className="pt-badge pt-badge-gray">{e.evidenceType.replace(/_/g, " ")}</span>{" "}
                    <strong>{e.label}</strong>
                  </span>
                  <span className="pt-muted" style={{ fontSize: "0.8rem" }}>{e.turnLabel}</span>
                </div>
                {e.studentExcerpt && (
                  <p style={{ margin: "8px 0 4px" }}>
                    <span className="pt-muted">Student: </span>“{e.studentExcerpt}”
                  </p>
                )}
                {e.explanation && <p className="pt-sub" style={{ margin: "4px 0" }}>{e.explanation}</p>}
                {e.suggestedAlternative && (
                  <p style={{ margin: "4px 0" }}>
                    <span className="pt-muted">Suggested better question: </span>
                    {e.suggestedAlternative}
                  </p>
                )}
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

/** Renders a completed AI assessment using the project's qualitative levels.
 * No numeric score is fabricated. Clearly labelled as AI-generated. */
export function AssessmentDisplay({ assessment }: { assessment: Assessment | null }) {
  if (!assessment) {
    return <div className="pt-muted">No assessment has been generated for this session.</div>;
  }
  if (assessment.status !== "COMPLETE" && assessment.status !== "NEEDS_REVIEW") {
    return (
      <div className="pt-muted">
        Assessment status: {assessment.status}. A completed assessment is not yet available.
      </div>
    );
  }
  return (
    <div>
      <div className="pt-card pt-section">
        <div className="pt-page-header" style={{ marginBottom: 8 }}>
          <h2 className="pt-h2" style={{ margin: 0 }}>
            Overall assessment
            <span className="pt-ai-tag">AI-generated</span>
          </h2>
          <LevelBadge level={assessment.overallLevel} />
        </div>
        {assessment.overallSummary && <p className="pt-sub" style={{ margin: 0 }}>{assessment.overallSummary}</p>}
      </div>

      {assessment.focusAreas.length > 0 && (
        <div className="pt-card pt-section">
          <h3 style={{ marginTop: 0 }}>Priority focus areas</h3>
          {assessment.focusAreas.map((f, i) => (
            <div key={i} style={{ marginBottom: 12 }}>
              <strong>{f.title}</strong>
              {f.whyItMatters && <p className="pt-sub" style={{ margin: "4px 0" }}>{f.whyItMatters}</p>}
              {f.suggestedPractice && (
                <p style={{ margin: "4px 0" }}>
                  <span className="pt-muted">Try: </span>{f.suggestedPractice}
                </p>
              )}
            </div>
          ))}
        </div>
      )}

      <h3>Domain results</h3>
      {assessment.domains.map((d) => (
        <DomainCard key={d.rubricDomain} d={d} />
      ))}

      <p className="pt-muted" style={{ fontSize: "0.8rem" }}>
        Generated by {assessment.modelName || "the AI assessor"} · rubric v{assessment.rubricVersion || "—"}
        {assessment.completedAt ? ` · ${new Date(assessment.completedAt).toLocaleString()}` : ""}
      </p>
    </div>
  );
}
