#!/usr/bin/env bash
#
# compile-lock.sh - The single sanctioned way to (re)generate
# backend/requirements.lock.txt from backend/requirements.txt. Resolves
# fully-pinned, hash-verified exact versions for Python 3.12 on Linux (the
# actual production target), regardless of the host this script runs on.
#
# backend/requirements.txt remains the human-authored source of intent
# (ranges, compatibility comments); backend/requirements.lock.txt is the
# authoritative install artifact prepare-release.sh actually uses. CI
# regenerates into a temp path with this exact script and diffs it against
# the committed lock - so this script's output must be deterministic given
# the same requirements.txt and uv version.
#
# Usage:
#   compile-lock.sh [--output <path>]
#
# --output defaults to backend/requirements.lock.txt (repo-relative). CI
# passes a temp path here to avoid touching the committed file.
#
# Exit codes:
#   0 - lock generated successfully
#   1 - bad arguments, missing prerequisites, or resolution failure
set -Eeuo pipefail

log() { echo "[compile-lock] $*" >&2; }
die() { log "ERROR: $*"; exit 1; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT="backend/requirements.lock.txt"

while [ $# -gt 0 ]; do
  case "$1" in
    --output) OUTPUT="${2:-}"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--output <path>]"
      exit 0
      ;;
    *) die "Unknown argument: $1" ;;
  esac
done

command -v uv >/dev/null 2>&1 || die "uv is required but not found on PATH"

# Run from the repo root and pass a repo-relative input path so the
# "autogenerated by uv via ..." header comment `uv pip compile` writes into
# the output records a clean, portable, repo-relative command line - not an
# absolute path tied to whatever machine/temp-directory happened to generate
# it. That header is part of the committed artifact and must be identical
# regardless of who runs this script or where the repo is checked out.
cd "$REPO_ROOT"
[ -f "backend/requirements.txt" ] || die "requirements.txt not found: $REPO_ROOT/backend/requirements.txt"

log "Compiling backend/requirements.txt -> $OUTPUT (python 3.12, linux, hashes)"
uv pip compile backend/requirements.txt \
  --python-version 3.12 \
  --python-platform linux \
  --generate-hashes \
  --output-file "$OUTPUT"

log "Done: $OUTPUT"
