#!/usr/bin/env bash
#
# prepare-release.sh - Stage a new immutable release under /opt/ptai/releases
# and ensure a matching content-addressed venv pair exists under
# /opt/ptai/venvs. Never touches /opt/ptai/current and never restarts any
# service - this script's entire job is to make a release READY to be
# activated, nothing more.
#
# Runs on the target EC2 instance (via SSM Run Command or SSH), not on the
# GitHub Actions runner.
#
# LESSON BAKED IN (Phase 3B-2 incident): venvs are built ONCE, directly at
# their final content-addressed path. They are never staged elsewhere and
# renamed/moved. uv/pip console-script shebangs embed the absolute
# install-time path; renaming after install silently breaks every wrapper
# script (uvicorn, alembic, ...) while `python -c "import ..."` checks keep
# passing. Verification below therefore executes the real binaries, not just
# the interpreter.
#
# LESSON BAKED IN (Phase 3B-3 incident): a venv/release path is NEVER treated
# as disposable merely because it lacks a `.ready` marker. `.ready` is a
# positive signal this script itself writes - its absence does not mean "safe
# to delete"; it may simply mean the path predates this convention (exactly
# what happened when this script deleted and rebuilt the live production venv
# out from under two running services that were never restarted only by
# chance). Before this script touches (deletes/rebuilds/renames) any existing
# venv path, it checks whether that path is actually referenced - by any
# release's .venv-hash, by 'current', by the rollback pointer, by a systemd
# unit's ExecStart, or by a running process's cmdline - and refuses outright
# if so. Only a path proven unreferenced by all of those checks is ever
# preserved-and-rebuilt, and even then it is renamed aside, never deleted.
#
# LOCKED DEPENDENCIES (dependency-locking checkpoint): venv content identity
# and installation are keyed on backend/requirements.lock.txt - a fully
# pinned, hash-verified artifact generated by scripts/deploy/compile-lock.sh
# - not on backend/requirements.txt, whose range constraints (`>=X,<Y`) make
# two installs from the identical file resolve to different concrete
# versions depending on when they run. This is what let the Phase 3B-3
# incident silently install different packages than what was live. The lock
# file must exist in the source checkout; if it's missing, this script stops
# with a clear error rather than ever falling back to resolving ranges.
# Install uses `--require-hashes`, so a hash mismatch (tampering, a stale
# local wheel cache, a resolver bug) fails loudly instead of installing
# something unverified.
#
# Usage:
#   prepare-release.sh --sha <full-40-char-git-sha> --source-dir <path>
#
# --source-dir must contain backend/ (with requirements.txt AND
# requirements.lock.txt) and dist/.
#
# Exit codes:
#   0 - release is ready (freshly built or already-ready, idempotent)
#   1 - bad arguments, missing prerequisites (including a missing lock
#       file), or build/verification failure
#   4 - refused: an existing venv path without .ready is actively referenced
#       by production (systemd, a running process, or a release/current/
#       rollback pointer) - manual investigation required, nothing was
#       deleted/rebuilt/renamed
set -Eeuo pipefail

log() { echo "[prepare-release] $*" >&2; }
die() { log "ERROR: $*"; exit 1; }

if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4))); then
  die "requires bash >= 4.4, found ${BASH_VERSION}"
fi

BASE_DIR="${PTAI_BASE_DIR:-/opt/ptai}"
RELEASES_DIR="$BASE_DIR/releases"
VENVS_DIR="$BASE_DIR/venvs"
SHARED_DIR="$BASE_DIR/shared"

SHA=""
SOURCE_DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --sha) SHA="${2:-}"; shift 2 ;;
    --source-dir) SOURCE_DIR="${2:-}"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 --sha <full-40-char-git-sha> --source-dir <path>"
      exit 0
      ;;
    *) die "Unknown argument: $1" ;;
  esac
done

[ -n "$SHA" ] || die "--sha is required"
[[ "$SHA" =~ ^[0-9a-f]{40}$ ]] || die "--sha must be a full 40-character lowercase hex git SHA, got: $SHA"
[ -n "$SOURCE_DIR" ] || die "--source-dir is required"
[ -d "$SOURCE_DIR" ] || die "source dir not found: $SOURCE_DIR"
[ -f "$SOURCE_DIR/backend/requirements.txt" ] || die "source dir missing backend/requirements.txt: $SOURCE_DIR"
[ -f "$SOURCE_DIR/backend/requirements.lock.txt" ] || die "source dir missing backend/requirements.lock.txt: $SOURCE_DIR -- this is the authoritative install artifact; generate it with scripts/deploy/compile-lock.sh and commit it. This script never falls back to resolving backend/requirements.txt's ranges directly."
[ -d "$SOURCE_DIR/dist" ] || die "source dir missing dist/: $SOURCE_DIR"

command -v uv >/dev/null 2>&1 || die "uv is required but not found on PATH"
command -v sha256sum >/dev/null 2>&1 || die "sha256sum is required but not found on PATH"
command -v rsync >/dev/null 2>&1 || die "rsync is required but not found on PATH"
[ -d "$RELEASES_DIR" ] || die "releases dir does not exist, expected prior bootstrap: $RELEASES_DIR"
[ -d "$VENVS_DIR" ] || die "venvs dir does not exist, expected prior bootstrap: $VENVS_DIR"

RELEASE_DIR="$RELEASES_DIR/$SHA"

if [ -f "$RELEASE_DIR/.ready" ]; then
  log "Release $SHA already prepared and marked ready ($RELEASE_DIR). Nothing to do."
  echo "$RELEASE_DIR"
  exit 0
fi

if [ -e "$RELEASE_DIR" ]; then
  die "Release directory exists but is NOT marked .ready: $RELEASE_DIR -- refusing to overwrite a possibly-partial prior attempt. Investigate and remove it manually (it is not referenced by 'current' or any rollback pointer unless activate-release.sh was already run for it, which would be a separate problem) before retrying."
fi

log "Preparing release $SHA from $SOURCE_DIR"
mkdir -p "$RELEASE_DIR"

# Secrets live only in /opt/ptai/shared/backend.env (the systemd
# EnvironmentFile), never inside a release directory. .env.example is
# harmless template content (no real values) and is preserved for
# reference; every other .env* file - the real secret - is excluded.
# Ordering matters: the --include exception must be listed before the
# broader --exclude that would otherwise also match it.
rsync -a \
  --include '.env.example' \
  --exclude '.env' \
  --exclude '.env.*' \
  --exclude '.git' \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  --exclude 'node_modules' \
  --exclude '.venv' \
  --exclude 'venv' \
  "$SOURCE_DIR/backend" "$RELEASE_DIR/"
rsync -a "$SOURCE_DIR/dist" "$RELEASE_DIR/"

# Post-copy validation: defense-in-depth, independent of the exclude rules
# above actually working as intended. A prepared release must never contain
# a real secrets file, regardless of how it was assembled.
FOUND_SECRETS=$(find "$RELEASE_DIR" -maxdepth 3 -type f -name '.env*' ! -name '.env.example' 2>/dev/null || true)
if [ -n "$FOUND_SECRETS" ]; then
  log "ERROR: prepared release contains disallowed secret-shaped file(s):"
  while IFS= read -r f; do [ -n "$f" ] && log "  - $f"; done <<< "$FOUND_SECRETS"
  rm -rf -- "$RELEASE_DIR"
  die "refusing to leave a release containing .env-like files on disk - release directory removed"
fi

REQ_FILE="$RELEASE_DIR/backend/requirements.txt"
[ -f "$REQ_FILE" ] || die "copied release is missing backend/requirements.txt: $REQ_FILE"
LOCK_FILE="$RELEASE_DIR/backend/requirements.lock.txt"
[ -f "$LOCK_FILE" ] || die "copied release is missing backend/requirements.lock.txt: $LOCK_FILE"

# Content-addressed on the LOCK file, not requirements.txt - see the header
# note above. Two releases with identical lock content always share a venv;
# two releases with identical requirements.txt but a regenerated lock
# (a legitimate dependency update) correctly get distinct venvs.
VENV_HASH=$(sha256sum "$LOCK_FILE" | awk '{print $1}')
VENV_ROOT="$VENVS_DIR/$VENV_HASH"
log "Lock file hash: $VENV_HASH"

# Determine whether an existing venv path (identified by its content-addressed
# hash directory) is referenced by anything real, independent of whether it
# has a .ready marker. Prints one reason per line and returns 0 if any
# reference was found, 1 if none were found. See the Phase 3B-3 incident note
# at the top of this file for why .ready alone can never be trusted for this.
is_venv_referenced() {
  local venv_path="$1"
  local venv_hash_dir
  venv_hash_dir=$(basename "$(dirname "$venv_path")")
  local -a reasons=()

  # Any release - .ready or not, current or not - that declares this exact
  # venv hash as its own. This is the most direct, filesystem-level source of
  # truth and alone would have caught the incident (the live release's
  # .venv-hash pointed at the venv this script deleted).
  local rd sha
  if [ -d "$RELEASES_DIR" ]; then
    for rd in "$RELEASES_DIR"/*/; do
      [ -d "$rd" ] || continue
      [ -f "${rd}.venv-hash" ] || continue
      if [ "$(cat "${rd}.venv-hash")" = "$venv_hash_dir" ]; then
        sha=$(basename "${rd%/}")
        reasons+=("release $sha declares this venv hash in .venv-hash")
      fi
    done
  fi

  # Is the release that owns this hash the active 'current'?
  if [ -L "$BASE_DIR/current" ]; then
    local current_sha
    current_sha=$(basename "$(readlink -f "$BASE_DIR/current")")
    if [ -f "$RELEASES_DIR/$current_sha/.venv-hash" ] \
       && [ "$(cat "$RELEASES_DIR/$current_sha/.venv-hash")" = "$venv_hash_dir" ]; then
      reasons+=("release $current_sha is the ACTIVE 'current' release")
    fi
  fi

  # Is the release that owns this hash the rollback target?
  if [ -f "$SHARED_DIR/rollback-pointer" ]; then
    local prev_sha
    # `|| true`: a no-match grep under pipefail would otherwise make this
    # assignment exit non-zero and, under `set -e`, silently abort the whole
    # script mid-build on a malformed pointer file - not just skip this check.
    prev_sha=$(grep -E '^previous_sha=' "$SHARED_DIR/rollback-pointer" | head -n1 | cut -d= -f2- || true)
    if [ -n "$prev_sha" ] && [ -f "$RELEASES_DIR/$prev_sha/.venv-hash" ] \
       && [ "$(cat "$RELEASES_DIR/$prev_sha/.venv-hash")" = "$venv_hash_dir" ]; then
      reasons+=("release $prev_sha is the ROLLBACK target")
    fi
  fi

  # Configured right now in a known systemd unit's ExecStart.
  if command -v systemctl >/dev/null 2>&1; then
    local unit
    for unit in ptai.service ptai-livekit-agent.service; do
      if systemctl show "$unit" -p ExecStart --no-pager 2>/dev/null | grep -qF "${venv_path}/"; then
        reasons+=("referenced by systemd unit $unit ExecStart")
      fi
    done
  else
    log "WARNING: systemctl not available -- systemd ExecStart reference check skipped for $venv_path"
  fi

  # Actually running right now, regardless of what systemd/config claims.
  # This is the check that directly prevents the Phase 3B-3 incident: it
  # catches a live process using this path even if every other signal above
  # is silent - e.g. a venv that predates the .venv-hash/.ready conventions
  # entirely, as the manually-repaired Phase 3B-2 venv did.
  local pid_dir pid
  for pid_dir in /proc/[0-9]*; do
    pid="${pid_dir#/proc/}"
    [ -r "$pid_dir/cmdline" ] || continue
    if tr '\0' ' ' < "$pid_dir/cmdline" 2>/dev/null | grep -qF "${venv_path}/"; then
      reasons+=("referenced by running process PID $pid (cmdline)")
    fi
  done

  if [ "${#reasons[@]}" -gt 0 ]; then
    printf '%s\n' "${reasons[@]}"
    return 0
  fi
  return 1
}

build_one_venv() {
  local venv_path="$1"
  local requirements_file="$2"
  local label="$3"

  if [ -f "$venv_path/.ready" ]; then
    log "$label venv already ready at $venv_path -- reusing, not rebuilding"
    return 0
  fi

  if [ -e "$venv_path" ]; then
    # No .ready does NOT mean "safe to delete" - it may only mean this path
    # predates the .ready convention while still being the live, in-use
    # venv (exactly what caused the Phase 3B-3 incident). Check real-world
    # references first, unconditionally, regardless of the marker.
    local refs
    if refs=$(is_venv_referenced "$venv_path"); then
      log "REFUSING to touch $label venv at $venv_path -- it lacks .ready but IS actively referenced:"
      while IFS= read -r r; do [ -n "$r" ] && log "  - $r"; done <<< "$refs"
      log "This requires manual investigation, not automated cleanup. If this venv is genuinely"
      log "sound (e.g. it predates the .ready convention), verify it manually - execute its real"
      log "binaries, run the isolated import checks - and only then create $venv_path/.ready by hand."
      exit 4
    fi

    # Not referenced by anything real - genuinely a stale/incomplete prior
    # attempt. Never destroy the only copy: preserve it with a deterministic
    # rename before building fresh.
    local backup_suffix
    backup_suffix=$(date -u +%Y%m%dT%H%M%SZ)
    local backup="${venv_path}.stale-${backup_suffix}"
    [ -e "$backup" ] && die "backup path already exists, refusing to overwrite: $backup"
    log "$label venv exists at $venv_path without .ready and is NOT referenced by anything live -- preserving as $backup before rebuild"
    mv -T -- "$venv_path" "$backup"
  fi

  log "Building $label venv directly at its final path: $venv_path"
  uv venv --python 3.12 "$venv_path" >&2
  # --require-hashes: uv refuses to install anything whose hash doesn't
  # exactly match the lock file - no silent substitution is possible even if
  # a package index serves a different artifact for the same version string.
  uv pip install --python "$venv_path/bin/python" -r "$requirements_file" --require-hashes >&2

  local py_version
  py_version=$("$venv_path/bin/python" --version 2>&1)
  case "$py_version" in
    "Python 3.12."*) ;;
    *) die "$label venv python version unexpected: $py_version" ;;
  esac

  # Execute the real binaries - this is the check that would have caught the
  # Phase 3B-2 stale-shebang bug immediately, versus `python -c "import"`
  # which invokes the interpreter directly and silently misses it.
  if [ -x "$venv_path/bin/uvicorn" ]; then
    "$venv_path/bin/uvicorn" --version >/dev/null 2>&1 \
      || die "$label venv: uvicorn binary failed to execute (possible stale shebang)"
  fi
  if [ -x "$venv_path/bin/alembic" ]; then
    "$venv_path/bin/alembic" --version >/dev/null 2>&1 \
      || die "$label venv: alembic binary failed to execute (possible stale shebang)"
  fi
  "$venv_path/bin/python" -c "import fastapi, sqlalchemy" >/dev/null 2>&1 \
    || die "$label venv: core import check failed"

  touch "$venv_path/.ready"
  log "$label venv verified and marked ready: $venv_path"
}

mkdir -p "$VENV_ROOT"
build_one_venv "$VENV_ROOT/backend" "$LOCK_FILE" "backend"
build_one_venv "$VENV_ROOT/livekit" "$LOCK_FILE" "livekit"

echo "$VENV_HASH" > "$RELEASE_DIR/.venv-hash"
touch "$RELEASE_DIR/.ready"

log "Release $SHA prepared successfully"
log "  release dir: $RELEASE_DIR"
log "  venv hash:   $VENV_HASH"
log "  venv dir:    $VENV_ROOT"
echo "$RELEASE_DIR"
